apiVersion: v1 
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80 # service port
      targetPort: 80 # application port
      nodePort: 30010 
  selector:
    app: myapp # this is compling from deployment.yaml:spec.template.metadata.labels.app
  