apiVersion: v1 
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP # this is defaule if nothing specified
  ports:
    - port: 80 # service port
      targetPort: 80 # application port

  selector:
    app: myapp # this is compling from deployment.yaml:spec.template.metadata.labels.app
  