apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: frontend
spec:
  template:
    # everything under template resembers pod.yaml
    metadata:
      name: nginx
      labels:
        app: nginx 
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3

  
  